version: '2'

services:
  seleniumWeb:
    # image: registry.cn-beijing.aliyuncs.com/tianli-spider/query-phone
    image: seleniums1
    restart: always
    ports:
      - 7890:7890
    command: python3 app.py 
    links:
      - redis:redis

  seleniumCookies:
    # image: registry.cn-beijing.aliyuncs.com/tianli-spider/query-phone
    image: seleniums1
    restart: always
    command: python3 sougou_cookie.py
    links:
      - redis:redis

  redis:
    image: redis:alpine
    restart: always
