version: '2'

services:
  selenium_app1:
    image: registry.cn-beijing.aliyuncs.com/tianli-spider/query-phone
    restart: always
    ports:
      - 7890:7890
    command: python3 app.py 
    links:
      - redis:redis

  selenium_app2:
    image: registry.cn-beijing.aliyuncs.com/tianli-spider/query-phone
    restart: always
    command: python3 sougou_cookie.py
    links:
      - redis:redis

  redis:
    image: redis:alpine
    restart: always
